discuss/urls.py
from django.urls import path

from discuss import views

app_name = 'discuss'

urlpatterns = [

    # 讨论区主页，每个主页显示10条Topic
    path('topics/', views.topics, name = 'topics'),

    # 创建新的Topic
    path('new_topic/', views.new_topic, name = 'new_topic'),

    # 显示Topic详细内容，按每页20条显示评论，可编辑添加评论
    path('topic/<int:topic_id>', views.topic, name = 'topic'),

    path('edit_topic/<int:topic_id>', views.edit_topic, name = 'edit_topic'),

    path('del_topic/<int:topic_id>', views.del_topic, name = 'del_topic'),

    path('new_discuss/<int:topic_id>', views.new_discuss, name = 'new_discuss'),

    path('del_discuss/<int:topic_id>/<int:dis_id>', views.del_discuss, name = 'del_discuss'),
]

lenote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Extension/', include('extension.urls', namespace='extension')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('lenotes.urls', namespace='lenotes')), 
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    #login
    path('login/', views.login_view, name = 'login'),
    #logout
    path('logout/', views.logout_view, name = 'logout'),
    #register
    path('register/', views.register, name = 'register'),
    
    path('home/', views.home, name = 'home'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    path('send_message/', views.send_message, name = 'send_message'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_invi/<int:invi_id><int:accept>',views.deal_invi, name = 'deal_invi' ),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),

    path('del_invi/<int:invi_id>', views.del_invi, name = 'del_invi'),
] 

discuss/models.py
from django.db import models
from markdownx.models import MarkdownxField
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length = 40, default="Undefined")
    content = MarkdownxField()
    date_added = models.DateTimeField(auto_now_add = True)
    topic_owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name='topic_owner')
    def __str__(self):
        return self.name

class Discuss(models.Model):
    content = MarkdownxField()
    mention = models.CharField(max_length = 60, default="")
    date_added = models.DateTimeField(auto_now_add = True)
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    discuss_owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name='discuss_owner')

discuss/forms.py
from django import forms
from discuss.models import Topic, Discuss
from markdownx.fields import MarkdownxFormField

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            'name',
            'content',
        ]
        labels = {
            'name' : 'Topic',
            'content' : 'Content ( Markdown supportted )',
        }
    def __init__(self, *args, **kwargs):
        super(TopicForm, self).__init__(*args, **kwargs)
        self.fields['content'] = MarkdownxFormField()
        self.fields['content'].label = 'Content ( Markdown supportted )'

class DiscussForm(forms.ModelForm):
    class Meta:
        model = Discuss
        fields = [ 
            'content', 
            'mention',
         ]
        
    def __init__(self, *args, **kwargs):
        super(DiscussForm, self).__init__(*args, **kwargs)
        self.fields['content'] = MarkdownxFormField()
        self.fields['mention'].label = 'Mention someone: '
        self.fields['mention'].initial = 'Example: "username1, username2"'

discuss/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from discuss.models import Topic, Discuss
from users.models import Message
from discuss.forms import TopicForm, DiscussForm

import re

@login_required
def check_topic_user(request, topic):
    if request.user != topic.topic_owner:
        raise Http404

@login_required
def topics(request, page = 0):
    topics = Topic.objects.order_by('date_added')[10*page : 10*page+10]
    context = { 'topics' : topics }
    return render(request, 'discuss/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    discuss_list = Discuss.objects.filter(topic = topic)
    form = DiscussForm()
    context = {'topic' : topic, 'discuss_list' : discuss_list, 'form': form}
    return render(request, 'discuss/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST, request.FILES)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.topic_owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('discuss:topics'))
    
    context = { 'form': form }
    return render(request, 'discuss/new_topic.html', context)

@login_required
def edit_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_user(request, topic)
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('discuss:topic', args=[topic_id]))
    context = {
        'topic' : topic,
        'form': form
    }
    return render(request, 'discuss/edit_topic.html', context)

@login_required
def del_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_user(request, topic)
    topic.delete()
    return HttpResponseRedirect(reverse('discuss:topics'))
    

@login_required
def new_discuss(request, topic_id):
    topic = Topic.objects.get(id = topic_id)
    if request.method != 'POST':
        form = DiscussForm()
    else:
        form = DiscussForm(request.POST)
        if form.is_valid():
            new_discuss = form.save(commit=False)
            new_discuss.topic = topic
            new_discuss.discuss_owner = request.user
            new_discuss.save()
            mention(request, new_discuss.mention, topic.name)
            return HttpResponseRedirect(reverse('discuss:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'discuss/topic.html', context)

@login_required
def mention(request, mention_list, topic_name):
    user_list = re.split('\W+', mention_list)
    for user in user_list:
        try:
            receiver_user = User.objects.get(username=user)
        except ObjectDoesNotExist:
            pass
        else:
            content = str(request.user) + " mention you in topic: " + topic_name
            Message.objects.create(sender=request.user.username, receiver=receiver_user, text=content, is_Read=False)

@login_required
def del_discuss(request, topic_id, dis_id):
    discuss = Discuss.objects.get(id=dis_id)
    discuss.delete()
    return HttpResponseRedirect(reverse('discuss:topic', args=[topic_id]))

discuss/templates/discuss/edit_topic.html
{% extends "lenotes/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Edit Topic:</h2>
{% endblock header %} {% block content %}

<form action="{% url 'discuss:edit_topic' topic.id %}" method='post' class="form">

    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button name="submit" class="btn btn-primary">Save change</button> {% endbuttons %}

</form>

{% endblock content %}

discuss/templates/discuss/new_topic.html
{% extends "lenotes/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Create new Topic:</h2>
{% endblock header %} {% block content %}

<form action="{% url 'discuss:new_topic' %}" method='post' class="form">

    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button name="submit" class="btn btn-primary">Create Topic</button> {% endbuttons %}

</form>

{% endblock content %}

discuss/templates/discuss/topic.html
{% extends "lenotes/base.html" %} {% load bootstrap3 %} {% load staticfiles %} {% load base %} {% block title %} Topics {% endblock %} {% block header %}
<h2>Topic</h2>
<script type="text/javascript">
    function delTopicConfirm() {
        event.returnValue = confirm("Are you sure to delete this topic?")
    }

    function delDiscussConfirm() {
        event.returnValue = confirm("Are you sure to delete this discuss?")
    }
</script>
{% endblock header %} {% block content %}
<hr>
<div class="section">
    <br/>
    <h3>{{topic.name}}</h3>
    <p>{{topic.topic_owner}} {{topic.date_added}}</p>
    <hr>
    <p>{{topic.content | custom_markdown }}</p>
</div>
{% ifequal request.user topic.topic_owner %}
<a href="{% url 'discuss:del_topic' topic.id %}" class="btn btn-danger" onclick="delTopicConfirm()">Delete Topic</a>
<a href="{% url 'discuss:edit_topic' topic.id %}" class="btn btn-primary">Edit Topic</a> {% endifequal %}

<br/>

<hr>
<div>
    <h3>Discuss</h3>
    {% for dis in discuss_list %}
    <hr>
    <p>{{ dis.date_added }} {{ dis.discuss_owner }} : {% if request.user == dis.discuss_owner %}
        <a href="{% url 'discuss:del_discuss' topic.id dis.id %}" title="Delete" onclick="delDiscussConfirm()">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
        {% elif request.user == topic.topic_owner %}
        <a href="{% url 'discuss:del_discuss' topic.id dis.id %}" title="Delete" onclick="delDiscussConfirm()">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
        {% endif %}</p> {{dis.content|custom_markdown}} {% empty %}
    <p>No discuss</p>
    {% endfor %}
</div>
<br/>

<hr>
<h4>Add your discuss</h4>
<form action="{% url 'discuss:new_discuss' topic.id %}" method='post' class="form">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button name="submit" class="btn btn-primary">Add discuss</button> {% endbuttons %}
</form>
{% endblock content %}

discuss/templates/discuss/topics.html
{% extends "lenotes/base.html" %} {% block title %} Topics {% endblock %} {% block content %}

<div class="section">
    <br/>
    <h2>Topics</h2>
    <br/>
    <table class="table table-hover">
        <thead>
            <tr>
                <td>Name</td>
                <td>Owner</td>
                <td>date added</td>
            </tr>
        </thead>
        <tbody>
            {% for topic in topics %}
            <tr>
                <td>{{ topic.name }}</td>
                <td>{{ topic.topic_owner }}</td>
                <td>{{ topic.date_added|date:'M d, Y H:i' }}</td>
                <td>
                    <a href="{% url 'discuss:topic' topic.id %}" title="View detail">
                        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a>
                </td>
            </tr>

            {% empty %}
            <tr>
                <td>No message.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'discuss:new_topic' %}">Create new topic</a>
</div>


{% endblock content %}