extension/urls.py
from django.urls import path

from extension import views

app_name = 'extension'

urlpatterns = [

    path('extend/', views.extend, name = 'extend'),
    
    path('about_us/', views.about_us, name = 'about_us'),

    path('embedding_info/', views.embedding_info, name = 'embedding_info'),

    path('extract_info/', views.extract_info, name = 'extract_info'),

    path('image_cutting/', views.image_cutting, name = 'image_cutting'),

    path('character_image/', views.character_image, name = 'character_image'),

    path('online_hash_verify/', views.online_hash_verify, name = 'online_hash_verify'),

    path('download_hash_verify/', views.download_hash_verify, name = 'download_hash_verify'),

    path('bagels/', views.bagels, name = 'bagels'),

    path('tiny_fish/', views.tiny_fish, name = 'tiny_fish'),
]

lenote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Extension/', include('extension.urls', namespace='extension')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('lenotes.urls', namespace='lenotes')), 
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lenotes/urls.py
from django.urls import path
import django.views
from lenotes import views

app_name = 'lenotes'

urlpatterns = [
    path('', views.index, name = 'index'),
    
    #path('group/', views.groups, name = 'groups'),

    path('group/<int:group_id>', views.group, name = 'group'),

    #path('group_diary/<int:group_id>/<int:diary_id>', views.group_diary, name = 'group_diary'),

    path('diary_month/<int:group_id>/<int:year>/<int:month>/<int:styleSelect>', views.diary_month, name = 'diary_month'),

    path('manage/<int:group_id>', views.manage, name = 'manage'),
    
    path('del_member/<int:group_id><int:info_id>', views.del_member, name = 'del_member'),

    path('send_invite/<int:group_id>', views.send_invite, name = 'send_invite'),

    path('new_group/', views.new_group, name = 'new_group'),

    path('del_group/<int:group_id>', views.del_group, name = 'del_group'),

    path('new_diary/<int:group_id>', views.new_diary, name = 'new_diary'),
    
    path('del_diary/<int:diary_id>', views.del_diary, name = 'del_diary'),

    path('add_diary/<int:group_id>', views.add_diary, name = 'add_diary'),

    path('edit_diary/<int:group_id>/<int:diary_id>', views.edit_diary, name = 'edit_diary'),

    path('edit_diary_md/<int:diary_id>', views.edit_diary_md, name = 'edit_diary_md'),

    path('diary_log/<int:diary_id>', views.diary_log, name = 'diary_log'),

    path('file_download', views.file_download, name = 'file_download'),

    path('upload_ajax/', views.upload_ajax, name='upload_ajax'),

    path('delete_ajax/', views.delete_ajax, name='delete_ajax'),

]

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    #login
    path('login/', views.login_view, name = 'login'),
    #logout
    path('logout/', views.logout_view, name = 'logout'),
    #register
    path('register/', views.register, name = 'register'),
    
    path('home/', views.home, name = 'home'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    path('send_message/', views.send_message, name = 'send_message'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_invi/<int:invi_id><int:accept>',views.deal_invi, name = 'deal_invi' ),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),

    path('del_invi/<int:invi_id>', views.del_invi, name = 'del_invi'),
] 

extension/models.py
from django.db import models

# Create your models here.

extension/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import Http404, HttpResponse
from django import forms

from PIL import Image
import numpy as np
import functools, zipfile, os, hashlib, random

# Create your views here.
def download_file(filename, aimname):
    file = open(filename, 'rb')  
    response = HttpResponse(file)  
    response['Content-Type'] = 'application/octet-stream'  
    response['Content-Disposition'] = f'attachment; filename = %s' % aimname  
    # response['Content-Disposition'] = f'attachment; filename = {"Text_embed.png"}'  
    return response 

def zip_dir(startdir, file_news):
    z = zipfile.ZipFile(file_news, 'w', zipfile.ZIP_DEFLATED) 
    for dirpath, dirnames, filenames in os.walk(startdir):
        fpath = dirpath.replace(startdir, '')
        fpath = fpath and fpath + os.sep or ''
        for filename in filenames:
            z.write(os.path.join(dirpath, filename), fpath+filename)
    z.close()

def extend(request):
    return render(request, 'extension/extension.html')

def about_us(request):
    return render(request, 'extension/about_us.html')

def embedding_info(request):
    if request.method == 'POST':
        text = request.POST['text']
        text = '#$#' + text
        text += '#%#' #作为结束标记
        
        img = request.FILES.get('beforeimg', None)
        
        if not img.name.endswith('.png'):
            raise Http404
        
        im = np.array(Image.open(img))        
        rows, columns, colors = im.shape
        embed = []
        for c in text:
            bin_sign = (bin(ord(c))[2:]).zfill(16)
            for i in range(16):
                embed.append(int(bin_sign[i]))
        
        count = 0
        for row in range(rows):
            for col in range(columns):
                for color in range(colors):
                    if count < len(embed):
                        im[row][col][color] = im[row][col][color] // 2 * 2 + embed[count]
                        count += 1

        # 这里将图片路径换成绝对路径，否则报错
        # /home/Lenote/media/Extensions/Text_embed.png
        Image.fromarray(im).save('media/Extensions/Text_embed.png')

        # /home/Lenote/media/Extensions/Text_embed.png
        return download_file('media/Extensions/Text_embed.png', 'Text_embed.png')

    return render(request, 'extension/embedding_info.html')
    

def extract_info(request):
    if request.method == 'POST':
        img = request.FILES.get('afterimg', None)

        if not img.name.endswith('.png'):
            raise Http404

        im = np.array(Image.open(img))
        rows, columns, colors = im.shape
        text = ""
        extract = np.array([], dtype = int)

        count = 0
        for row in range(rows):
            for col in range(columns):
                for color in range(colors):
                    extract = np.append(extract, im[row][col][color] % 2)
                    count += 1
                    if count % 16 == 0:
                        bcode = functools.reduce(lambda x, y: str(x) + str(y), extract)
                        cur_char = chr(int(bcode, 2))
                        text += cur_char
                        if len(text) == 3 and text != '#$#':
                            content = { 'text':'非标准格式文件，无法解密' }
                            return render(request, 'extension/extract_info.html', content)
                        if cur_char == '#' and text[-3:] == '#%#':
                            content = { 'text':text[3:-3] }
                            return render(request, 'extension/extract_info.html', content)
                        extract = np.array([], dtype=int)

    return render(request, 'extension/extract_info.html')

def image_cutting(request):
    if request.method == 'POST':
        img = request.FILES.get('img', None)
        imgformat = request.POST['format']
        filename = img.name

        accept_format = ['png', 'jpg', 'peg', 'bmp']
        if img.name[-3:] not in accept_format:
            raise Http404

        for root, dirs, files in os.walk("media/Extensions/image_cutting", topdown=False):
            for name in files:
                os.remove(os.path.join(root, name))

        rows, columns = int(imgformat[0]), int(imgformat[-1])
        img = Image.open(img)
        w, h = img.size
        rowheight = h // rows
        colwidth = w // columns
        for r in range(rows):
            for c in range(columns):
                box = (c * colwidth, r * rowheight, (c + 1) * colwidth, (r + 1) * rowheight)
                i = img.crop(box)
                i.save('media/Extensions/image_cutting/' + filename[:-4] + str(r*3+c) + filename[-4:])

        startdir = "media/Extensions/image_cutting" 
        file_news = "media/Extensions/image_cutting.zip"
        zip_dir(startdir, file_news)
        
        return download_file('media/Extensions/image_cutting.zip', 'image_cutting.zip')

    return render(request, 'extension/image_cutting.html')

# 将256灰度映射到70个字符上
ascii_char = list(r"$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\|()1{}[]?-_+~<>i!lI;:,\"^`'. ")

def get_char(r, g, b, alpha = 256):
    if alpha == 0:
        return ' '
    length = len(ascii_char)
    gray = int(0.2126 * r + 0.7152 * g + 0.0722 * b)

    unit = (256.0 + 1) / length
    return ascii_char[int(gray/unit)]

# 检查长宽是否在可接受范围内以及输入时候正确
def check_wh(src, default):
    try :
        src = int(src)
    except:
        src = default
    else:
        src = default if src not in list(range(10, 150)) else src
    return src

def character_image(request):
    if request.method == 'POST':
        img = request.FILES.get('img', None)
        imgformat = request.POST['format']
        
        accept_format = ['png', 'jpg', 'peg', 'bmp'] #peg -> jpeg
        if img.name[-3:] not in accept_format:
            raise Http404

        im = Image.open(img)
        w, h = im.size

        height = request.POST['height']
        height = check_wh(height, 80)
        try:
            autowidth = request.POST['autowidth']
        except Exception as e:
            width = request.POST['width']
            width = check_wh(width, 120)
        else:
            width = w * height // h
        
        im = im.resize((width, height), Image.NEAREST)

        txt = ""

        for i in range(height):
            for j in range(width):
                txt += get_char(*im.getpixel((j, i)))
            txt += '\n'

        with open('media/Extensions/character_image.txt', 'w') as f_obj:
            f_obj.write(txt)
             
        return download_file('media/Extensions/character_image.txt', 'character_image.txt')

    return render(request, 'extension/character_image.html')

def online_hash_verify(request):
    if request.method == 'POST':
        file = request.FILES.get('file', None)

        with open('media/Extensions/'+file.name, 'wb+') as f:
            for chunk in file.chunks():
                f.write(chunk)

        content = {}
        algorithm_names = ['md5', 'sha1', 'sha256', 'sha512']

        for name in algorithm_names:
            algorithm = hashlib.new(name)

            # read 1M one time
            read_size = 1024*1024
            with open('media/Extensions/'+file.name, 'rb') as f:
                while True:
                    b = f.read(read_size)
                    if b:
                        algorithm.update(b)
                    else:
                        break

            content[name] = algorithm.hexdigest()

        os.remove('media/Extensions/'+file.name)
        return render(request, 'extension/online_hash_verify.html', content)

    return render(request, 'extension/online_hash_verify.html')

def download_hash_verify(request):
    return download_file('media/Extensions/hash_verify.zip', 'hash_verify.zip')

def tiny_fish(request):
    return render(request, 'extension/tiny_fish.html')


# bagels 

NUM_DIGITS = 3
MAX_GUESS = 10

def getSecretNum():
    # 返回一个由 NUM_DIGITS 个不重复随机数组成的字符串
    numbers = list(range(10))
    random.shuffle(numbers)
    secretNum = ''
    for i in range(NUM_DIGITS):
        secretNum += str(numbers[i])
    return secretNum

def getClues(guess, secretNum):
    # 返回一个由 Pico, Fermi 和 Bagels 组成的，用来提示用户的字符串
    if guess == secretNum:
        return 'You got it!'

    clues = []
    for i in range(len(guess)):
        if guess[i] == secretNum[i]:
            clues.append('Fermi')
        elif guess[i] in secretNum:
            clues.append('Pico')
    if len(clues) == 0:
        return 'Bagels'

    clues.sort()
    return ' '.join(clues)

def bagels(request):
    secretNum = getSecretNum()
    guessesTaken = 1

    if request.method == 'POST':
        content = {}
        num1, num2, num3 = request.POST['number1'], request.POST['number2'], request.POST['number3']
        guess = str(num1) + str(num2) + str(num3)
        content['result'] = getClues(guess, secretNum)
        guessesTaken += 1
        if guess == secretNum:
            pass
        if guessesTaken > MAX_GUESS:
            print('You ran out of guesses. The answer was %s.' % (secretNum))
    content = { 'names':['number1', 'number2', 'number3'], 'number':[i for i in range(0, 10)]}
    return render(request, 'extension/bagels.html', content)

extension/templates/extension/about_us.html
{% extends "lenotes/base.html" %} {% block title %} About Us {% endblock %} {% block content %}

<div class="section">
    <br/>
    <h2>About Us</h2>
    <p>
        Lenote is a GPL product from <a href="https://github.com/Schnee-Cy/Lenote">Lenote</a>
    </p>
    <p>
        GPL v3 licensed by <a href="https://github.com/Schnee-Cy/Lenote">Lenote</a>
    </p>
    <br/>
    <h2>Designers and Developers</h2>
    <h5>Yiyan Sun <a href="https://github.com/sunyiyan123">https://github.com/sunyiyan123</a></h5>
    <h5>Zihuang Su <a href="https://github.com/Schnee-Cy">https://github.com/Schnee-Cy</a></h5>
    <h5>Shenghao Qiu <a href="https://github.com/oqsh">https://github.com/oqsh</a></h5>
    <h5>Jiangxin Sun <a href="https://github.com/I-Am-Yours">https://github.com/I-Am-Yours</a></h5>
    <br/>
    <a href="{% url 'lenotes:file_download' %}">点击此处下载 帮助手册</a>
</div>

{% endblock content %}

extension/templates/extension/bagels.html
{% extends "lenotes/base.html" %} {% load static %} {% block title %} Image cutting {% endblock %} {% block content %}

<div class="section">
    <br/>
    <h2>Bagels</h2>
    <br/>
    <p>Bagels 是可以和朋友一起玩的一个推理游戏。你的朋友想到一个随机的、没有重复的3位数字，你尝试去猜测它是什么。每次猜测之后，朋友就会给出3种类型的线索：</p>
    <ul>
        <li>Bagels：你猜测的3个数都不在神秘数字中；</li>
        <li>Pico：你猜测的是神秘数字中的一个数，但是位置不对；</li>
        <li>Fermi：你猜测的是正确位置上的一个正确的数。</li>
    </ul>
    <p>计算机会提示多条线索，这些线索按照字母顺序排序。若神秘数字是 456，而你的猜测是 546，那么线索就是“fermi pico pico”。6 提供的线索是“fermi”，5 和 4 提供的线索是“pico pico”</p>
    <br/>
    <form action="{% url 'extension:image_cutting' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}
        <div class="form-group" align="center">
            {% for n in names %}
            <div class="col-md-4">
                <select class="form-control" name="n">
            {% for i in number %}
                <option>{{i}}</option>
            {% endfor %}
            </select>
            </div>
            {% endfor %}
            <br/>
            <br/>
            <button type="submit" class="btn btn-primary">Comfirm</button>
        </div>
    </form>
</div>
{% endblock %}

extension/templates/extension/character_image.html
{% extends "lenotes/base.html" %} {% load static %} {% block title %}character image{% endblock %} {% block content %}

<title>选中复选框，相关类变灰</title>
<script language="JavaScript">
    function selectKind(the) {
        var obj = the;
        var container = document.getElementById("kind_" + obj.name);
        for (var i = 0; i < container.getElementsByTagName("input").length; i++) {
            container.getElementsByTagName("input")[i].disabled = obj.checked;
        }
    }
</script>

<div class="section">
    <br/>
    <h2>Character Image</h2>
    <br/>
    <div align="center">
        <br/>
        <img src="{% static 'img/charcater_image_example1.jpg' %}" alt="example1" />
        <img src="{% static 'img/arrow.jpg' %}" alt="arrow" />
        <img src="{% static 'img/charcater_image_example2.jpg' %}" alt="example2" />
        <p style="font-size:20px">Example</p>
        <br/>
    </div>
    <br/>
    <form action="{% url 'extension:character_image' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}
        <div class="form-group ">
            <label>Format:</label>
            <select class="form-control" name="format">
                    <option value="Default">Default</option>
            </select>
            <br/>
            <label>Height: (10 - 150 default: 80)</label>
            <input type="text" class="form-control" placeholder="Text input" name='height'>
            <br/>
            <label>
                Width: (10 - 150 default: 120)
                <input type='checkbox' value='1' name='autowidth' checked="checked" onclick="selectKind(this)"> Adjust width automatically
            </label>
            <div id="kind_autowidth">
                <input type="text" class="form-control" placeholder="Text input" name='width' disabled="disabled">
            </div>
            <br/>
            <label for='img'>Image (only support: png, bmp, jpg, jpeg)</label>
            <input type='file' name='img' class='form-control' />
            <br/>
            <button type='submit' class='btn btn-primary'>Comfirm</button>
        </div>
    </form>

</div>

{% endblock content %}

extension/templates/extension/embedding_info.html
{% extends "lenotes/base.html" %} {% block title %} Embedding info {% endblock %} {% block content %}

<div class="section">
    <br/>
    <h2>Embedding info</h2>
    <br/>
    <p>PS: Provide a picture (PNG format) and a paragraph of text. Click comfirm to embed the text into picture.</p>

    <form action="{% url 'extension:embedding_info' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}

        <div class="form-group">
            <label for='text'>Text</label>
            <input type='text' class='form-control' name='text'>
            <br/>
            <label for='beforeimg'>Image (.png only or 404)</label>
            <input type='file' name='beforeimg' class='form-control' />
            <br/>
            <button type="submit" class="btn btn-primary">Comfirm</button>
        </div>
    </form>

</div>

{% endblock content %}

extension/templates/extension/extension.html
{% extends "lenotes/base.html" %} {% block title %} Extensions {% endblock %} {% block content %} {% block header %} {% load static %}


<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Extensions.css' %}">
</head>

{% endblock %}

<body background="{% static 'img/Extensions_background1.png' %}">
    <div class="section" align="center">
        <h1>Extensions</h1>
        <p>
            Something new only for testing and entertainment.
        </p>
        <br/>
        <div style="width:1140px;height:300px">
            <h3>Image</h3>
            <div id="nav">
                <p style="font-size:20px"><strong>Text embed:</strong></p>
                <p>Provide a picture (PNG format) and a text.</p>
                <p>Embedding the text into picture using 'Embedding info'</p>
                <p>and extracting the text using 'Extract info'</p>
                <li><a href="{% url 'extension:embedding_info' %}">Embedding info</a></li>
                <li><a href="{% url 'extension:extract_info' %}">Extract info</a></li>
            </div>
            <div id="nav">
                <p style="font-size:20px"><strong>Image cutting</strong></p>
                <p>Image cutting: Cut an image into some small image.</p>
                <p>Provide cut image into 2 * 2, 2 * 3, 3 * 3</p>
                <p>which can be used in Wechat Moments.</p>
                <li><a href="{% url 'extension:image_cutting' %}">Image cutting</a></li>
            </div>
            <div id="nav">
                <p style="font-size:20px"><strong>Character Image</strong></p>
                <p>Converting pictures into character drawings</p>
                <p>Provide serveral modes for you</p>
                <li><a href="{% url 'extension:character_image' %}">Character Image</a></li>
            </div>
        </div>
        <!-- <div style="width:1140px;height:300px">
            <h3>Game</h3>
            <div id="nav">
                <p style="font-size:20px"><strong>Bagels</strong></p>
                <p>Samll game of number guess</p>
                <li><a href="{% url 'extension:bagels' %}">Bagels</a></li>
            </div>
            <div id="nav">
                <p style="font-size:20px"><strong>Tiny Fish</strong></p>
                <p>Mini game for relaxed, just enjoy it!</p>
                <p>Copy from: <a href='https://github.com/CruxF/IMOOC/tree/master/HTML5/H5GameNext'>Github: Tinyfish</a></p>
                <p>I will try to realization again by myself.</p>
                <p>coming soon</p>
                <li><a href="{% url 'extension:tiny_fish' %}">Tiny Fish</a></li>
            </div>
        </div> -->
        <div style="width:1140px;height:300px">
            <h3>Security</h3>
            <div id="nav">
                <p style="font-size:20px"><strong>Hash Verification</strong></p>
                <p>Verify the hash value of the file</p>
                <p>Provide Validation mode:</p>
                <p>md5, sha-1, sha-256, sha-512</p>
                <li><a href="{% url 'extension:online_hash_verify' %}">Online Verification</a></li>
                <li><a href="{% url 'extension:download_hash_verify' %}">Download Program</a></li>
            </div>
        </div>
        <div style="width:1140px;height:300px">
            <h3>Others</h3>
            <div id="nav">
                <p style="font-size:20px"><strong> Coming soon...</strong></p>
            </div>
        </div>
    </div>
</body>

{% endblock content %}

extension/templates/extension/extract_info.html
{% extends "lenotes/base.html" %} {% block title %} Extract info {% endblock %} {% block content %}

<div class="section">
    <br/>
    <h2>Extract info</h2>
    <br/>
    <P>PS: Provice a Image with infomation, we will check it's format and extracting the text.</P>

    <form action="{% url 'extension:extract_info' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}

        <div class="form-group">
            <label for='afterimg'>Image (.png only or 404)</label>
            <input type='file' name='afterimg' class='form-control' />
            <br/>
            <button type="submit" class="btn btn-primary">Comfirm</button>
        </div>
    </form>
    <p>{{ text }}</p>

</div>

{% endblock content %}

extension/templates/extension/image_cutting.html
{% extends "lenotes/base.html" %} {% load static %} {% block title %} Image cutting {% endblock %} {% block content %}

<div class="section">
    <br/>
    <h2>Image cutting</h2>
    <br/>
    <div align="center">
        <br/>
        <img src="{% static 'img/example1.jpg' %}" alt="example1" />
        <img src="{% static 'img/arrow.jpg' %}" alt="arrow" />
        <img src="{% static 'img/example2.jpg' %}" alt="example2" />
        <p style="font-size:20px">Example</p>
        <br/>
    </div>
    <br/>
    <form action="{% url 'extension:image_cutting' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}
        <div class="form-group ">
            <label>Format:</label>
            <select class="form-control" name="format">
                    <option value="3,3">3 * 3</option>
                    <option value="2,3">2 * 3</option>
                    <option value="2,2">2 * 2</option>
            </select>
            <label for='img'>Image (only support: png, bmp, jpg, jpeg)</label>
            <input type='file' name='img' class='form-control' />
            <br/>
            <button type="submit" class="btn btn-primary">Comfirm</button>
        </div>
    </form>

</div>

{% endblock content %}

extension/templates/extension/online_hash_verify.html
{% extends "lenotes/base.html" %} {% block title %} Extract info {% endblock %} {% block content %}

<div class="section">
    <br/>
    <h2>Online hash verify</h2>
    <br/>
    <P>PS: Provice a file and we will calculates its hash value.</P>

    <form action="{% url 'extension:online_hash_verify' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}

        <div class="form-group">
            <label for='afterimg'>File (PS: size <= 16M)</label>
            <input type='file' name='file' class='form-control' />
            <br/>
            <button type="submit" class="btn btn-primary">Comfirm</button>
        </div>
    </form>
    {% ifnotequal md5 None %}
    <p>md5: {{ md5 }}</p>
    <p>sha-1: {{ sha1 }}</p>
    <p>sha-256: {{ sha256 }}</p>
    <p>sha-512: {{ sha512 }}</p>
    {% endifnotequal %}
</div>

{% endblock content %}

extension/templates/extension/retro_snaker.html
<!doctype html>
<html>

<body>
    <canvas id="can" width="400" height="400" style="background: Black"></canvas>
    <script>
        var sn = [42, 41],
            dz = 43,
            fx = 1,
            n, ctx = document.getElementById("can").getContext("2d");

        function draw(t, c) {
            ctx.fillStyle = c;
            ctx.fillRect(t % 20 * 20 + 1, ~~(t / 20) * 20 + 1, 18, 18);
        }
        document.onkeydown = function(e) {
            fx = sn[1] - sn[0] == (n = [-1, -20, 1, 20][(e || event).keyCode - 37] || fx) ? fx : n
        };
        ! function() {
            sn.unshift(n = sn[0] + fx);
            if (sn.indexOf(n, 1) > 0 || n < 0 || n > 399 || fx == 1 && n % 20 == 0 || fx == -1 && n % 20 == 19)
                return alert("GAME OVER");
            draw(n, "Lime");
            if (n == dz) {
                while (sn.indexOf(dz = ~~(Math.random() * 400)) >= 0);
                draw(dz, "Yellow");
            } else
                draw(sn.pop(), "Black");
            setTimeout(arguments.callee, 130);
        }();
    </script>
</body>

</html>

extension/templates/extension/tiny_fish.html
{% extends "lenotes/base.html" %} {% block header %} {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <title></title>
    <style>
        body {
            padding-top: 10px;
        }
        
        .all-bg {
            width: 1140px;
            height: 600px;
            margin: 0 auto;
        }
        
        #allcanvas {
            position: relative;
            width: 1140px;
            height: 600px;
            margin: 0;
        }
        
        #canvas1 {
            position: absolute;
            bottom: 0;
            left: 0;
            z-index: 1;
        }
        
        #canvas2 {
            position: absolute;
            bottom: 0;
            left: 0;
            z-index: 0;
        }
    </style>
</head>

<body>
    <div class="all_bg" style="align:center">
        <div id="allcanvas">
            <canvas id="canvas1" width="1140" height="600"></canvas>
            <canvas id="canvas2" width="1140" height="600"></canvas>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/commonFunctions.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/background.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ane.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/fruit.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mom.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/collision.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/baby.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/data.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/wave.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/halo.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dust.js' %}"></script>
</body>

</html>


{% endblock %}