extension/urls.py
from django.urls import path

from extension import views

app_name = 'extension'

urlpatterns = [

    path('extend/', views.extend, name = 'extend'),
    
    path('about_us/', views.about_us, name = 'about_us'),

    path('embedding_info/', views.embedding_info, name = 'embedding_info'),

    path('extract_info/', views.extract_info, name = 'extract_info'),

    path('image_cutting/', views.image_cutting, name = 'image_cutting'),

    path('character_image/', views.character_image, name = 'character_image'),

    path('online_hash_verify/', views.online_hash_verify, name = 'online_hash_verify'),

    path('download_hash_verify/', views.download_hash_verify, name = 'download_hash_verify'),

    path('bagels/', views.bagels, name = 'bagels'),

    path('tiny_fish/', views.tiny_fish, name = 'tiny_fish'),
]

lenote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Extension/', include('extension.urls', namespace='extension')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('lenotes.urls', namespace='lenotes')), 
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lenotes/urls.py
from django.urls import path
import django.views
from lenotes import views

app_name = 'lenotes'

urlpatterns = [
    path('', views.index, name = 'index'),
    
    #path('group/', views.groups, name = 'groups'),

    path('group/<int:group_id>', views.group, name = 'group'),

    #path('group_diary/<int:group_id>/<int:diary_id>', views.group_diary, name = 'group_diary'),

    path('diary_month/<int:group_id>/<int:year>/<int:month>/<int:styleSelect>', views.diary_month, name = 'diary_month'),

    path('manage/<int:group_id>', views.manage, name = 'manage'),
    
    path('del_member/<int:group_id><int:info_id>', views.del_member, name = 'del_member'),

    path('send_invite/<int:group_id>', views.send_invite, name = 'send_invite'),

    path('new_group/', views.new_group, name = 'new_group'),

    path('del_group/<int:group_id>', views.del_group, name = 'del_group'),

    path('new_diary/<int:group_id>', views.new_diary, name = 'new_diary'),
    
    path('del_diary/<int:diary_id>', views.del_diary, name = 'del_diary'),

    path('add_diary/<int:group_id>', views.add_diary, name = 'add_diary'),

    path('edit_diary/<int:group_id>/<int:diary_id>', views.edit_diary, name = 'edit_diary'),

    path('edit_diary_md/<int:diary_id>', views.edit_diary_md, name = 'edit_diary_md'),

    path('diary_log/<int:diary_id>', views.diary_log, name = 'diary_log'),

    path('file_download', views.file_download, name = 'file_download'),

    path('upload_ajax/', views.upload_ajax, name='upload_ajax'),

    path('delete_ajax/', views.delete_ajax, name='delete_ajax'),

]

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    #login
    path('login/', views.login_view, name = 'login'),
    #logout
    path('logout/', views.logout_view, name = 'logout'),
    #register
    path('register/', views.register, name = 'register'),
    
    path('home/', views.home, name = 'home'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    path('send_message/', views.send_message, name = 'send_message'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_invi/<int:invi_id><int:accept>',views.deal_invi, name = 'deal_invi' ),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),

    path('del_invi/<int:invi_id>', views.del_invi, name = 'del_invi'),
] 

lenotes/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from datetime import datetime
# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length = 40, default="example group")
    intro = models.CharField(max_length = 200, default="no introduce")
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name='group_owner')
    members = models.ManyToManyField(User)
    profile = ProcessedImageField(upload_to='group/img', default='group/img/default.jpg', 
        processors=[ResizeToFill(750, 465)],  format='JPEG', options={'quality': 60})
    def __str__(self):
        return self.name

class Diary(models.Model):
    content = MarkdownxField()
    date_added = models.DateTimeField(auto_now_add = True)
    group = models.ForeignKey(Group,on_delete = models.CASCADE)
    diary_log = models.TextField(default=str(datetime.now()) + "  Create diary")
    def __str__(self):
        return self.content[:30] + '...'

class Invitation(models.Model): 
    invite_id = models.CharField(max_length = 40) 
    message = models.CharField(max_length = 200)  
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add = True)
    groupid = models.IntegerField()
    is_Read = models.BooleanField(default = False)
    def __str__(self):
        return self.message

class Imgele(models.Model):
    belong = models.ForeignKey(Diary, on_delete=models.CASCADE)
    idname = models.CharField(max_length = 40)
    img = models.ImageField(upload_to='diary/img')
    zindex = models.IntegerField(default = 999)
    w = models.FloatField(default = 300)
    h = models.FloatField(default = 300)
    x = models.FloatField(default = 0)
    y = models.FloatField(default = 0)


class Textele(models.Model):
    belong = models.ForeignKey(Diary, on_delete=models.CASCADE)
    idname = models.CharField(max_length = 40)
    content = models.TextField(default='Input something please')
    x = models.FloatField(default = 0) 
    y = models.FloatField(default = 0)
    fontsize = models.IntegerField(default = 40)
    fontcolor = models.CharField(max_length = 20, default='black')
    zindex = models.IntegerField(default = 999)

lenotes/forms.py
from django import forms
from lenotes.models import Group, Diary, Invitation
from markdownx.fields import MarkdownxFormField

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'name',
            'intro',
        ]
        labels = {
            'name': 'Group Name',
            'intro': 'Group Introduce',
        }

class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = [
            'content',
        ]
        labels = {
            'content' : 'Content ( Markdown supportted )',
        }
    def __init__(self, *args, **kwargs):
        super(DiaryForm, self).__init__(*args, **kwargs)
        self.fields['content'] = MarkdownxFormField()
        self.fields['content'].label = 'Content ( Markdown supportted )'

class InvitationForm(forms.ModelForm):
    class Meta:
        model = Invitation
        fields = ['invite_id']
        labels = {'invite_id': 'Invite ID'}
    def get_id(self):
        return self.fields['invite_id'] 

lenotes/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404, StreamingHttpResponse, HttpResponse
from django.shortcuts import render

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from lenotes.models import Group, Diary, Invitation, Imgele, Textele
from users.models import UserInfo, Message
from lenotes.forms import GroupForm, DiaryForm, InvitationForm
from users.views import update_userInfo_unread_count

from datetime import datetime
from PIL import Image

import json

def check_user(request, group, flag): 
    """
        flag 0 检查是不是群主
        flag 1 检查是不是群成员
    """
    if flag == 0 and request.user != group.owner:
        raise Http404
    elif flag == 1 and request.user not in group.members.all():
        raise Http404


@login_required
def delete_ajax(request):
    del_id = request.POST.get("del_id")
    if(del_id[0]=='t'):
        de = Textele.objects.get(id= int(del_id[3:]))
        de.delete()
    elif(del_id[0]=='p'):
        de = Imgele.objects.get(id= int(del_id[3:]))
        de.delete()
    return HttpResponse('')


@login_required
def upload_ajax(request):
    data = json.loads(request.body.decode('utf-8'))
    for key,value in data.items():
        if key[0]=='t':
            idx = int(key[3:])
            tex = Textele.objects.get(id = idx)
            tex.content = value['content']
            s = value['x']
            tex.x = float(s[:len(s)-2])
            s = value['y']
            tex.y = float(s[:len(s)-2])
            tex.zindex = int(value['z'])
            s = value['fontsize']
            tex.fontsize = int(s[:len(s)-2])
            tex.fontcolor = value['fontcolor']
            tex.save()
        elif key[0]=='p':
            idx = int(key[3:])
            pic = Imgele.objects.get(id = idx)
            s = value['x']
            pic.x = float(s[:len(s)-2])
            s = value['y']
            pic.y = float(s[:len(s)-2])
            s = value['w']
            pic.w = float(s[:len(s)-2])
            s = value['h']
            pic.h = float(s[:len(s)-2])
            pic.zindex = int(value['z'])
            pic.save()
    return HttpResponse('')



def index(request):
    if request.user.is_authenticated:
        update_userInfo_unread_count(request.user)
    return render(request, 'lenotes/new_index.html')

@login_required
def group(request, group_id):
    """群组主页"""
    year = datetime.now().year
    month = datetime.now().month
    return HttpResponseRedirect(reverse('lenotes:diary_month', args=[group_id, year, month, 1]))

@login_required   
def diary_month(request, group_id, year, month, styleSelect):
    get_group = Group.objects.get(id=group_id)
    check_user(request, get_group, 1)
    tdiary = get_group.diary_set.order_by('-date_added')
    createJudge = False
    if tdiary.count()==0:
        createJudge = True
    elif tdiary[0].date_added.year != datetime.now().year or tdiary[0].date_added.month != datetime.now().month\
        or tdiary[0].date_added.day != datetime.now().day:
        createJudge = True  

    diarys = get_group.diary_set.filter(date_added__year=year, date_added__month = month)
    odiarys = diarys.order_by('date_added')    
    lastMonth, lastYear, nextMonth, nextYear = 1, 1, 1, 1
    
    lastMonthJudge = True
    if tdiary.count() == 0 or month==tdiary[len(tdiary)-1].date_added.month:
        lastMonthJudge = False
    if month==1:
        lastMonth = 12
        lastYear = year-1
    else:
        lastMonth = month-1
        lastYear = year

    nextMonthJudge = True
    if month==datetime.now().month:
        nextMonthJudge = False
    
    if month==12:
        nextMonth = 1
        nextYear = year+1
    else:
        nextMonth = month+1
        nextYear = year
    
    context = {
        'group': get_group, 
        'odiarys': odiarys, 
        'createJudge': createJudge,
        'nowYear': year,
        'nowMonth': month,
        'lastMonth': lastMonth,
        'lastYear': lastYear,
        'lastMonthJudge': lastMonthJudge,
        'nextMonthJudge': nextMonthJudge,
        'nextMonth': nextMonth,
        'nextYear': nextYear,
    }
    if styleSelect == 1:
        return render(request, 'lenotes/group_diary_md.html', context)
    elif styleSelect == 2:
        return render(request, 'lenotes/group_diary.html', context)

# # 压缩图片尺寸
# def compressImage(image):
#     tmp_image = Image.open(image)
#     width = tmp_image.width 
#     height = tmp_image.height
#     rate = 1.0 # 压缩率

#     # 根据图像大小设置压缩率
#     if width >= 3000 or height >= 3000:
#         rate = 0.15  
#     elif width >= 2000 or height >= 2000:
#         rate = 0.3
#     elif width >= 1000 or height >= 1000:
#         rate = 0.7
#     elif width >= 500 or height >= 500:
#         rate = 0.9

#     width = int(width * rate)   # 新的宽
#     height = int(height * rate) # 新的高

#     tmp_image.thumbnail((width, height), Image.ANTIALIAS) # 生成缩略图
#     tmp_image.save('media/group/img/' + str(image))

@login_required
def manage(request, group_id):
    """修改群组资料，邀请功能，管理用户"""
    if request.method != 'POST':
        try:
            group = Group.objects.get(id=group_id)
        except ObjectDoesNotExist:
            group = Group.objects.create(id=group_id)
        group_form = GroupForm(instance = group)
    else:
        group_form = GroupForm(request.POST, request.FILES)
        if group_form.is_valid():
            try:
                group = Group.objects.get(id=group_id)
            except ObjectDoesNotExist:
                group = Group.objects.create(id=group_id)
        group.name = group_form.cleaned_data["name"]
        group.intro = group_form.cleaned_data["intro"]
        myprofile = request.FILES.get('profile',None)
        if myprofile:
            if group.profile.name != 'group/img/default.jpg':
                group.profile.delete()
            group.profile = myprofile
        group.save()
        return HttpResponseRedirect(reverse('lenotes:group', args=[group.id]))
    
    check_user(request, group, 1)
    members = group.members.all()
    memberInfos = []
    for member in members:
        info = UserInfo.objects.get(user=member)
        memberInfos.append(info)
    context = {
        'group': group,
        'memberInfos': memberInfos,
        'group_form': group_form,
    }
    return render(request, 'lenotes/manage.html' , context)

@login_required
def del_member(request, group_id, info_id):
    group = Group.objects.get(id=group_id)
    check_user(request, group, 0)
    info = UserInfo.objects.get(id=info_id)
    group.members.remove(info.user)
    msg = "You have been removed from group: " + group.name
    Message.objects.create(sender = group.owner.username + "(Group Owner)", text=msg, receiver=info.user)
    return HttpResponseRedirect(reverse('lenotes:manage', args=[group_id]))

@login_required
def send_invite(request, group_id):
    if request.method == 'POST':
        try:
            invite_user = User.objects.get(username=request.POST['invite_id'])
        except ObjectDoesNotExist:
            context = {'group_id': group_id}
            return render(request, 'lenotes/userIsNotExist.html' , context)
        group = Group.objects.get(id = group_id)
        check_user(request, group, 0)
        msg = request.user.username + " invite you to join Group: " + group.name 
        Invitation.objects.create(receiver=invite_user, message=msg, groupid=group_id, is_Read=False)
        return HttpResponseRedirect(reverse('lenotes:manage', args=[group_id]))
    group = Group.objects.get(id = group_id)
    check_user(request, group, 0)
    context = { 'group_id': group_id }
    return render(request, 'lenotes/send_invite.html', context)

@login_required
def new_group(request):
    if request.method != 'POST':
        form = GroupForm()
    else:
        form = GroupForm(request.POST, request.FILES)
        if form.is_valid():
            new_group = form.save(commit=False)
            new_group.owner = request.user
            new_group.save()
            new_group.members.add(request.user)
            new_group.save()
            return HttpResponseRedirect(reverse('users:home'))
    
    context = { 'form': form }
    return render(request, 'lenotes/new_group.html', context)

@login_required
def del_group(request, group_id):
    """删除当前群组"""
    del_group = Group.objects.get(id=group_id)
    check_user(request, del_group, 0)
    members = del_group.members.all()
    senderName = del_group.owner.username + "(Group Owner)"
    for member in members:
        msg = "The group: " + del_group.name + " have been deleted."
        Message.objects.create(sender=senderName, text=msg, receiver=member)
    del_group.delete()
    return HttpResponseRedirect(reverse('users:home'))

@login_required
def new_diary(request, group_id):
    group = Group.objects.get(id = group_id)
    check_user(request, group, 1)
    if request.method != 'POST':
        form = DiaryForm()
    else:
        form = DiaryForm(data = request.POST)
        if form.is_valid():
            new_diary = form.save(commit=False)
            new_diary.group = group
            new_diary.save()
            return HttpResponseRedirect(reverse('lenotes:group', args=[group_id]))
    context = {'group': group, 'form': form}
    return render(request, 'lenotes/new_diary.html', context)

@login_required
def edit_diary(request, group_id, diary_id):
    diary = Diary.objects.get(id = diary_id)
    if request.method == 'POST':
        obj = request.FILES.get('Imgfield',None)
        if obj:
            new_img = Imgele.objects.create(img = obj, belong = diary)
            new_img.idname = "IMG" + str(new_img.id)
            new_img.w = 100
            new_img.h = 100
            new_img.save()
        tex = request.POST.get('newText', None)
        if tex:
            new_text = Textele.objects.create(belong=diary, content=tex)
            new_text.idname = "TEXT" + str(new_text.id)

lenotes/templates/lenotes/base.html
{% load bootstrap3 %}{% load staticfiles %}{% load base %}
<!DOCTYPE html>
<style>
    .myimg {
        width: 120px;
        height: 50px;
        padding: 15px 15px 15px 0px;
    }
</style>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lenote</title>

    {% bootstrap_css %} {% bootstrap_javascript %}

</head>

<body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                </button>
                <a href="{% url 'lenotes:index' %}">
                    <img class="myimg" src="{% static 'img/logo.png' %}" alt="" />
                </a>
            </div>

            <div id="navbar" class="navbar-collapse collapse" style="width: 1070px height: 50px">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'users:home' %}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'extension:extend' %}">Extensions</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'extension:about_us' %}">About us</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:notice' %}" class="btn btn-default" style="margin-top: 7px">Notice 
                        {% ifnotequal user|getUnreadCount 0 %}
                        <span class="badge ">{{ user|getUnreadCount }}</span>
                        {% endifnotequal %}
                    </a>
                    <div class="btn-group">
                        <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="margin-top: 7px">{{user.username}}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="userMenu">
                            <li role="presentation"><a class="dropdown-item" href="{% url 'users:reset_password' %}">Reset Password</a></li>
                            <li role="presentation"><a class="dropdown-item" href="{% url 'users:send_message' %}">Send Message</a></li>
                            <li role="presentation"><a class="dropdown-item" href="{% url 'users:settings' %}">Settings</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation"><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'users:login' %}?next={{request.path}}" class="btn btn-default" style="margin-top: 7px">Log In</a>
                        <a href="{% url 'users:register' %}" class="btn btn-default" style="margin-top: 7px">Register</a>
                    </form>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>

    <div class="container">
        <div>
            {% block header %}{% endblock %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>

    </div>

</body>

</html>

lenotes/templates/lenotes/group.html
{% extends 'lenotes/base.html' %} {% block header %}
<h2>{{ group }}</h2>
{% endblock header %} {% block content %}
<p>
    {{group.intro}}
    <ul class="nav navbar-nav navbar-right">
        <a class="btn btn-default" href="{% url 'lenotes:manage' group.id %}" role="button">Manage</a>
    </ul>
</p>

<div>
    <p></p>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Diary</th>
            <th>Create Time</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
        {% for diary in diarys %}
        <tr>
            <td><a href="{% url 'lenotes:edit_diary' diary.id %}">{{ diary.name }}</a></td>
            <td>{{ diary.date_added|date:'M d, Y H:i' }}</td>
            <td>{{ diary }}</td>
            <td>
                <a href="{% url 'lenotes:del_diary' diary.id %}" title="Delete">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <li>No diary have been created yet.</li>
        {% endfor %}
    </tbody>
</table>
<p>
    <a href="{% url 'lenotes:new_diary' group.id %}" class="btn btn-default">create new diary</a>
</p>
{% endblock content %}

lenotes/templates/lenotes/group_diary.html
{% extends 'lenotes/base.html' %} {% load bootstrap3 %}{% load staticfiles %}{% load base %} {% block header %}
<h2>{{ group }}</h2>
{% endblock header %} {% block content %}
<p>
    {{group.intro}}
    </br>
    </br>
    <ul class="nav navbar-nav navbar-right">
        <a class="btn btn-default" href="{% url 'lenotes:diary_month' group.id nowYear nowMonth 1 %}" role="button">Markdown style</a>
        <!-- <a class="btn btn-default" href="#" role="button" title="还没有做完哦，以后更新~" disabled>Free style</a> -->
        <!--以后写完free style删除这一行用上一行-->
        <a class="btn btn-default" href="{% url 'lenotes:manage' group.id %}" role="button">Manage</a>
    </ul>
</p>
<li>
    {% if lastMonthJudge %}
    <a href="{% url 'lenotes:diary_month' group.id lastYear lastMonth 1 %}" class="btn btn-default">Last month</a> {% endif %} {% if nextMonthJudge %}
    <a href="{% url 'lenotes:diary_month' group.id nextYear nextMonth 1 %}" class="btn btn-default">Next month</a> {% endif %} {% if createJudge %}
    <a href="{% url 'lenotes:new_diary' group.id %}" class="btn btn-default">create new diary</a> {% endif %}
</li>



<meta name="viewport" content="width=device-width, initial-scale=1">

<link href='https://fonts.googleapis.com/css?family=Playfair+Display:700,900|Fira+Sans:400,400italic' rel='stylesheet' type='text/css'> {% load static %}

<link rel="stylesheet" href="{% static 'css/diary_style.css' %}">
<!-- Resource style -->
<script src="{% static 'js/modernizr.js' %}"></script>
<!-- Modernizr -->
<script src="{% static 'js/jquery-2.1.4.js' %}"></script>
<script src="{% static 'js/jquery.mobile.custom.min.js' %}"></script>
<script src="{% static 'js/diary_main.js' %}"></script>
<!-- Resource jQuery -->

<div>
    <section class="cd-horizontal-timeline">
        <div class="timeline">
            <div class="events-wrapper">
                <div class="events">
                    <ol>
                        {% for diary in odiarys %} {% if forloop.last %}
                        <li><a href="#0" data-date="{{diary.date_added|date:'d/m/Y'}}" class="selected">{{diary.date_added|date:'m.d'}}</a></li>
                        {% else %}
                        <li><a href="#0" data-date="{{diary.date_added|date:'d/m/Y'}}">{{diary.date_added|date:'m.d'}}</a></li>
                        {% endif %} {% empty %}
                        <li>
                            <a data-date="01/02/2013" class="selected"></a>
                            <li>
                                {% endfor %}
                    </ol>

                    <span class="filling-line" aria-hidden="true"></span>
                </div>
                <!-- .events -->
            </div>
            <!-- .events-wrapper -->

            <ul class="cd-timeline-navigation">
                <li><a href="#0" class="prev inactive">Prev</a></li>
                <li><a href="#0" class="next">Next</a></li>
            </ul>
            <!-- .cd-timeline-navigation -->
        </div>
        <!-- .timeline -->

        <div class="events-content">
            <ol>

                {% for diary in odiarys %} {% if forloop.last %}
                <li data-date="{{diary.date_added|date:'d/m/Y'}}" class="selected">
                <div id="MainContent" style="height: 600px; border:6px outset; border-color:yellowgreen">
                    {% for tex in diary.textele_set.all %}
                    <div id="tex{{tex.id}}" style="position: absolute; left: {{tex.x}}px;  top: {{tex.y}}px; z-index:{{tex.zindex}};
                    font-size: {{tex.fontsize}}px; color: {{tex.fontcolor}}; 
                    ">{{tex.content}}</div>
                    {% endfor %}

                    {% for pic in diary.imgele_set.all %}
                    <div id="pic{{pic.id}}" style="position: absolute; left: {{pic.x}}px;  
                    width: {{pic.w}}px; height: {{pic.h}}px; z-index: {{pic.zindex}};
                    top: {{pic.y}}px;"><img src="/media/{{pic.img}}" style="width: 100%; height:100%; " alt=""></div>
                    {% endfor %}
                </div>
                    <br/>
                    <a href="{% url 'lenotes:edit_diary' group.id diary.id %}" class="btn btn-default">Edit today</a>
                </li> 
                {% else %}
                <li data-date="{{diary.date_added|date:'d/m/Y'}}">
                <div id="MainContent" style="height: 600px; border:6px outset; border-color:yellowgreen">
                    {% for tex in diary.textele_set.all %}
                    <div id="tex{{tex.id}}" style="position: absolute; left: {{tex.x}}px;  top: {{tex.y}}px; z-index:{{tex.zindex}};
                    font-size: {{tex.fontsize}}px; color: {{tex.fontcolor}}; 
                    ">{{tex.content}}</div>
                    {% endfor %}

                    {% for pic in diary.imgele_set.all %}
                    <div id="pic{{pic.id}}" style="position: absolute; left: {{pic.x}}px;  
                    width: {{pic.w}}px; height: {{pic.h}}px; z-index: {{pic.zindex}};
                    top: {{pic.y}}px;"><img src="/media/{{pic.img}}" style="width: 100%; height:100%; " alt=""></div>
                    {% endfor %}
                </div>
                    <br/>
                    <a href="{% url 'lenotes:edit_diary' group.id diary.id %}" class="btn btn-default">Edit today</a>
                </li>
                {% endif %} {% empty %}
                <li class="selected">
                    <div style="height: 300px;">
                        这个月没日记哦·····
                    </div>
                </li>
                {% endfor %}


            </ol>
        </div>
        <!-- .events-content -->

        {% if createJudge %}
</div>
<p>
    <a href="{% url 'lenotes:new_diary' group.id %}" class="btn btn-default">create new diary</a>
</p>
</section>
{% endif %} {% endblock content %}

lenotes/templates/lenotes/old_group.html
{% extends 'lenotes/base.html' %} {% block header %}
<h2>{{ group }}</h2>
{% endblock header %} {% block content %}
<p>
    {{group.intro}}
    <ul class="nav navbar-nav navbar-right">
        <a class="btn btn-default" href="{% url 'lenotes:manage' group.id %}" role="button">Manage</a>
    </ul>
</p>

<div>
    <p></p>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Diary</th>
            <th>Create Time</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
        {% for diary in diarys %}
        <tr>
            <td><a href="{% url 'lenotes:edit_diary' diary.id %}">{{ diary.name }}</a></td>
            <td>{{ diary.date_added|date:'M d, Y H:i' }}</td>
            <td>{{ diary }}</td>
            <td>
                <a href="{% url 'lenotes:del_diary' diary.id %}" title="Delete">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <li>No diary have been created yet.</li>
        {% endfor %}
    </tbody>
</table>
<p>
    <a href="{% url 'lenotes:new_diary' group.id %}" class="btn btn-default">create new diary</a>
</p>
{% endblock content %}