lenote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Extension/', include('extension.urls', namespace='extension')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('lenotes.urls', namespace='lenotes')), 
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lenotes/urls.py
from django.urls import path
import django.views
from lenotes import views

app_name = 'lenotes'

urlpatterns = [
    path('', views.index, name = 'index'),
    
    #path('group/', views.groups, name = 'groups'),

    path('group/<int:group_id>', views.group, name = 'group'),

    #path('group_diary/<int:group_id>/<int:diary_id>', views.group_diary, name = 'group_diary'),

    path('diary_month/<int:group_id>/<int:year>/<int:month>/<int:styleSelect>', views.diary_month, name = 'diary_month'),

    path('manage/<int:group_id>', views.manage, name = 'manage'),
    
    path('del_member/<int:group_id><int:info_id>', views.del_member, name = 'del_member'),

    path('send_invite/<int:group_id>', views.send_invite, name = 'send_invite'),

    path('new_group/', views.new_group, name = 'new_group'),

    path('del_group/<int:group_id>', views.del_group, name = 'del_group'),

    path('new_diary/<int:group_id>', views.new_diary, name = 'new_diary'),
    
    path('del_diary/<int:diary_id>', views.del_diary, name = 'del_diary'),

    path('add_diary/<int:group_id>', views.add_diary, name = 'add_diary'),

    path('edit_diary/<int:group_id>/<int:diary_id>', views.edit_diary, name = 'edit_diary'),

    path('edit_diary_md/<int:diary_id>', views.edit_diary_md, name = 'edit_diary_md'),

    path('diary_log/<int:diary_id>', views.diary_log, name = 'diary_log'),

    path('file_download', views.file_download, name = 'file_download'),

    path('upload_ajax/', views.upload_ajax, name='upload_ajax'),

    path('delete_ajax/', views.delete_ajax, name='delete_ajax'),

]

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    #login
    path('login/', views.login_view, name = 'login'),
    #logout
    path('logout/', views.logout_view, name = 'logout'),
    #register
    path('register/', views.register, name = 'register'),
    
    path('home/', views.home, name = 'home'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    path('send_message/', views.send_message, name = 'send_message'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_invi/<int:invi_id><int:accept>',views.deal_invi, name = 'deal_invi' ),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),

    path('del_invi/<int:invi_id>', views.del_invi, name = 'del_invi'),
] 

users/models.py
from django.db import models
from django.contrib.auth.models import User
from lenotes.models import Group
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.

class UserInfo(models.Model):
    GENDER_CHOICES = (
        (u'M', u'Male'),
        (u'F', u'Female'),
    )
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    name = models.CharField(max_length = 20, default = "Undefined")
    gender = models.CharField(max_length = 6, choices = GENDER_CHOICES, default = "Male")
    email = models.CharField(max_length = 40, default = "Undefined@example.com")
    intro = models.CharField(max_length = 200, default = "hello world")
    profile = ProcessedImageField(upload_to='user/img', default='user/img/default.jpg', 
        processors=[ResizeToFill(500, 500)],  format='JPEG', options={'quality': 60})
    unread_count = models.IntegerField(default=0)
    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.CharField(max_length = 20)
    text = models.CharField(max_length = 300)
    date_added = models.DateTimeField(auto_now_add = True)
    receiver = models.ForeignKey(User, on_delete = models.CASCADE)
    is_Read = models.BooleanField(default = False)
    def __str__(self):
        return self.text

users/forms.py
from django import forms
#from markdown import MarkdownFormField
from users.models import UserInfo, Message


#class ProfileForm(forms.Form):
 #   upProfile = forms.FileField()

class InfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = [
            'name',
            'gender',
            'email',
            'intro',
        
        ]
        labels = {
            'name': 'User Name',
            'gender': 'Gender',
            'email': 'Email',
            'intro': 'User introduce',
        }

class MsgForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = [
            'receiver',
            'text',
        ]
        labels = {
            'receiver' : 'Receiver',
            'text': ''
        }

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from users.models import UserInfo, Message
from lenotes.models import Group, Invitation
from users.forms import InfoForm, MsgForm #, ProfileForm

def update_userInfo_unread_count(user):
    userinfo = UserInfo.objects.get(user=user) 
    userinfo.unread_count = Message.objects.filter(receiver=user, is_Read=False).count() +\
        Invitation.objects.filter(receiver=user, is_Read=False).count()
    userinfo.save()

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('lenotes:index'))
    if request.method != 'POST':
        form = AuthenticationForm(request)
    else:
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return HttpResponseRedirect(reverse('lenotes:index'))
    context = {'form': form}
    return render(request, 'users/login.html', context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('lenotes:index'))

def register(request):
    if request.method != 'POST':
        user_form = UserCreationForm()
        info_form = InfoForm()
    else:
        print(request.POST)
        user_form = UserCreationForm(data=request.POST)
        info_form = InfoForm(request.POST, request.FILES)
        if user_form.is_valid():
            new_user = user_form.save()
            new_info = info_form.save(commit=False)
            new_info.user = new_user
            new_info.save()
            authenticated_user = authenticate(username = new_user.username,
            password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('lenotes:index'))
    
    context = {
        'user_form': user_form,
        'info_form': info_form,    
    }
    return render(request, 'users/register.html' , context)

@login_required
def home(request):
    """显示个人信息的主界面"""
    try:
        userinfo = UserInfo.objects.get(user=request.user) 
    except ObjectDoesNotExist:
        userinfo = UserInfo.objects.create(user=request.user)
    if userinfo.name.strip() == "":
        userinfo.name = "Undefined"
    if userinfo.gender.strip() == "M":
        userinfo.gender = "Male"
    else:
        userinfo.gender = "Female"
    if userinfo.email.strip() == "":
        userinfo.email = "Undefined@example.com"
    if userinfo.intro.strip() == "":
        userinfo.intro = "No introduce"
    update_userInfo_unread_count(request.user)
    groups = Group.objects.filter(members__id = request.user.id).order_by('date_added')
    context = {
        'userinfo': userinfo,
        'groups' : groups,
    }
    return render(request, 'users/home.html', context)

@login_required
def settings(request):
    if request.method != 'POST':
        try:
            info = UserInfo.objects.get(user = request.user)
        except ObjectDoesNotExist:
            info = UserInfo.objects.create(user = request.user)
        info_form = InfoForm(instance = info)
        context = {
        'info_form': info_form,
        }
        return render(request, 'users/settings.html' , context)
    else:
        info_form = InfoForm(request.POST)
        if info_form.is_valid():
            try:
                info = UserInfo.objects.get(user = request.user)
            except ObjectDoesNotExist:
                info = UserInfo.objects.create(user = request.user)
        info.name = info_form.cleaned_data["name"]
        info.gender = info_form.cleaned_data["gender"]
        info.email = info_form.cleaned_data["email"]
        info.intro = info_form.cleaned_data["intro"]
        myprofile = request.FILES.get('profile',None)
        if myprofile:
            if info.profile.name != 'user/img/default.jpg' :
                info.profile.delete()
            info.profile = myprofile
        info.save()
        return HttpResponseRedirect(reverse('users:home'))
    

@login_required
def reset_password(request):
    if request.method != 'POST':
        form = PasswordChangeForm(user = request.user)
    else:
        form = PasswordChangeForm(user = request.user, data = request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(reverse('users:reset_done'))
    context = {
        'form': form, 
    }
    return render(request, 'users/reset_password.html', context)

def reset_done(request):
    return render(request, 'users/reset_done.html')

@login_required
def notice(request):
    """用于接收留言以及通知"""
    update_userInfo_unread_count(request.user)
    messages = Message.objects.filter(receiver = request.user).order_by('-date_added')
    invitations = Invitation.objects.filter(receiver=request.user).order_by('-date_added')
    context = {
        'messages': messages,
        'invitations': invitations
    }
    return render(request, 'users/notice.html', context)

@login_required
def send_message(request):
    """向某人发送信息"""
    if request.method == 'POST':
        try:
            receiver_user = User.objects.get(username=request.POST['receiver_id'])
        except ObjectDoesNotExist:
            return render(request, 'lenotes/userIsNotExist.html')
        content = request.POST['content']
        Message.objects.create(sender=request.user.username, receiver=receiver_user,text=content, is_Read=False)
        return HttpResponseRedirect(reverse('users:home'))
    return render(request, 'users/send_message.html')

@login_required
def read_message(request, message_id):
    """标记消息为已读"""
    try:
        message = Message.objects.get(id=message_id)
        message.is_Read = True;
        message.save()
    finally:
        return HttpResponseRedirect(reverse('users:notice'))

@login_required
def del_message(request, message_id):
    """删除当前消息"""
    try:
        del_message = Message.objects.get(id=message_id)
        del_message.delete()
    finally:
        return HttpResponseRedirect(reverse('users:notice'))

@login_required
def deal_invi(request, invi_id, accept):
    """处理邀请"""
    try:
        invitation = Invitation.objects.get(id=invi_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('users:notice')) 
    invitation.is_Read = True
    invitation.save()
    if accept:
        group = Group.objects.get(id=invitation.groupid)
        group.members.add(invitation.receiver)
        msg = request.user.username + " accpeted to join in group:" + group.name
    else:
        msg = request.user.username + " refused to join in group:" + group.name
    Message.objects.create(sender=request.user.username, text=msg, receiver=group.owner)
    return HttpResponseRedirect(reverse('users:notice'))

@login_required
def quit_group(request, group_id):
    """退出当前群聊"""
    try:
        group = Group.objects.get(id=group_id)
        group.members.remove(request.user)
        msg = request.user.username + " quit the group: " + group.name
        Message.objects.create(sender=request.user.username + "(Group Member)", text=msg, receiver=group.owner)
    finally:
        return HttpResponseRedirect(reverse('users:home'))

@login_required
def del_invi(request, invi_id):
    """删除当前通知"""
    try:
        del_invitation = Invitation.objects.get(id=invi_id)
        del_invitation.delete()
    finally:
        return HttpResponseRedirect(reverse('users:notice'))

users/templates/users/home.html
{% extends "lenotes/base.html" %} {% block header %} {% load static %}
<html>

<head>
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/homestyle.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
</head>

<body>
    <div class="banner-body">
        <div class="container">
            <div style='width: 800px;height:100px;'>
                <div style="margin:0 0 0 290px; float: left;">
                    <img class="img-circle" style="width:150px;height:150px;overflow:hidden;" src="/media/{{userinfo.profile}}" alt="">
                </div>
                <div style="float: right;" class="top-nav">
                    <nav class="navbar navbar-default1">
                        <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                            <nav class="stroke">
                                <ul class="nav navbar-nav1">
                                    <li>
                                        <div style="float:left; font-size: 30px; font-family: 'Open Sans'">{{userinfo.name}}</div>
                                        <div style="padding: 20px;font-size: 10px;float:left; font-family: 'Open Sans'">{{userinfo.gender}}</div>
                                    </li>
                                    <br/>
                                    <li>
                                        <div class='email_info'>{{userinfo.email}}</div>
                                    </li>
                                    <br/>
                                    <li>
                                        <div class='user_info'>{{userinfo.intro}}</div>
                                    </li>

                                </ul>
                            </nav>
                        </div>
                    </nav>
                </div>
            </div>
            <div style='margin:0 auto;'>
                <br/>
                <br/>
                <br/>
                <div class="line_divide_group"></div>
                <br/>
                <br/>
                <br/>

                <div class="msg-text-bottom">
                    {% for group in groups %}
                    <div class="msg-text-bottom-left" style="width: 280px; height: 320px;  float: left;">
                        <figure class="effect-winston">
                            <a href="{% url 'lenotes:group' group.id %} "><img src="/media/{{group.profile}}" alt=" " class="img-responsive" />
                            </a>
                        </figure>
                        <h3><a href="{% url 'lenotes:group' group.id %} ">{{ group.name }}</a></h3>
                        <p class='my_content'>{{ group.intro }}</p>
                        <br/>
                    </div>
                    {% endfor %}
                    <div class="clearfix"> </div>
                </div>
                <br/>
                <br/>
                <h4><a href="{% url 'lenotes:new_group' %} " class="btn btn-default creat_group_button">Create new group</a></h4>
                <br/>
                <br/>
            </div>
        </div>
    </div>
</body>

</html>

{% endblock %}

users/templates/users/login.html
{% extends "lenotes/base.html" %} {% load staticfiles %} {% load widget_tweaks %} {% block title %}Log in{% endblock title %} {% block stylesheet %} {% endblock stylesheet %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<style>
    body {
        background-image:url("{% static 'img/background.jpg' %}");
        background-repeat: no-repeat;
        background-position: 50% -30%;
    }
</style>

<body>

    <div class="section">
        {% if user.is_authenticated %}
        <p>You have login. Go back to <a href="/">index</a></p>
        {% else %}
        <div class="mycontainer" style="margin-top: 340px">
            <form class="" method="post" action="{% url 'users:login' %}" novalidate>
                {% csrf_token %} {% if form.errors %}
                <p style="text-align: center; color: grey; font-size: 24px; ">Incorrect username or password.</p>
        </div class="col-xs-4">
        {% endif %}
        <label for="id_username" class="form-control sr-only">Username</label> {{ form.username | add_class:"form-control" | attr:"placeholder:Username"}}
        <p></p>
        <label for="id_password" class="form-control sr-only">Password</label> {{ form.password | add_class:"form-control" | attr:"placeholder:Password"}}
        <p></p>
        <center>
            <button class="btn btn-primary form-control-button" type="submit" name="submit">Log in</button>
        </center>
        <input type="hidden" name="next" value="{{ next }}" />
        </form>
    </div>
    {% endif %}
    </div>
</body>
{% endblock content %}

users/templates/users/notice.html
{% extends "lenotes/base.html" %} {% block header %}
<h1>Notices</h1>
{% endblock %} {% block content %}

<table class="table table-hover">
    <thead>
        <tr>
            <th>Message</th>
            <th>Sender</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
        {% for message in messages %} {% ifequal message.is_Read False %}
        <tr class="info">
            <td>{{ message.date_added|date:'M d, Y H:i' }}</td>
            <td>{{ message.sender }}</td>
            <td>{{ message.text }}</td>
            <td>
                <a href="{% url 'users:read_message' message.id %}" title="Comfire">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                </a>
            </td>

        </tr>
        {% else %}
        <tr>
            <td>{{ message.date_added|date:'M d, Y H:i' }}</td>
            <td>{{ message.sender }}</td>
            <td>{{ message.text }}</td>
            <td>
                <a href="{% url 'users:del_message' message.id %}" title="Delete">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>

            </td>
        </tr>
        {% endifequal %} {% empty %}
        <tr>
            <td>No message.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<p></p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Invite</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
        {% for invitation in invitations %} {% ifequal invitation.is_Read False %}
        <tr class="info">
            <td>{{ invitation.date_added|date:'M d, Y H:i' }}</td>
            <td>{{ invitation.message }}</td>
            <td>
                <a href="{% url 'users:deal_invi' invitation.id 1 %}" title="Accept">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                </a>
            </td>
            <td>
                <a href="{% url 'users:deal_invi' invitation.id 0 %}" title="Refuse">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        {% else %}
        <tr>
            <td>{{ invitation.date_added|date:'M d, Y H:i' }}</td>
            <td>{{ invitation.message }}</td>
            <td>
                <a href="{% url 'users:del_invi' invitation.id %}" title="Delete">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        {% endifequal %} {% empty %}
        <tr>
            <td>No invite.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h4><a href="{% url 'users:home' %}" class="btn btn-default">Go Back</a></h4>

{% endblock content %}

users/templates/users/old_home.html
{% extends "lenotes/base.html" %} {% block header %} {% load static %}
<div style="width: 200px; height: 200px;">
    <img style="width:200px;height:200px;overflow:hidden;" src="/media/{{userinfo.profile}}" alt="">
</div>

<h2><strong>{{userinfo.name}}</strong> <small>{{userinfo.gender}}</small></h2>
<h4>{{userinfo.email}}</h4>
<h3>{{userinfo.intro}}</h3>

<p></p>
{% endblock header %} {% block content %}

<table class="table table-hover ">
    <thead>
        <tr>
            <th>Groups</th>
            <th>Introduce</th>
        </tr>
    </thead>
    <tbody>
        {% for group in groups %}
        <tr>
            <td><a href="{% url 'lenotes:group' group.id %} ">{{ group.name }}</a></td>
            <td>{{group.intro}}</td>
        </tr>
        {% empty %}
        <li>No group have been created yet.</li>
        {% endfor %}
    </tbody>
</table>

<h4><a href="{% url 'lenotes:new_group' %} " class="btn btn-default ">Create new group</a></h4>

{% endblock content %}

users/templates/users/register.html
{% extends "lenotes/base.html" %} {% load widget_tweaks %} {% block title %}Register{% endblock title %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
<div class="section">
    <form class="form-users" method="post" enctype="multipart/form-data" action="{% url 'users:register' %}">
        {% csrf_token %}
        <center>
            <h2>Register</h2>
        </center>
        <hr>
        <div class="form-group form-register">
            {% include 'users/forms/user_form.html' %} {% include 'users/forms/info_form.html' %}
        </div>
        <div style="text-align: center">
            <button name="submit" class="btn btn-primary">Register</button>
            <a class="btn btn-outline-primary" href="/">Go Back</a>
        </div>
        <input type="hidden" name="next" value="{% url 'lenotes:index' %}" />
    </form>
    <div style="text-align: center">
        <p>Have an account? <a href="{% url 'users:login' %}">Click</a> to log in.</p>
    </div>
</div>
{% endblock content %}

users/templates/users/reset_done.html
{% extends "lenotes/base.html" %} {% load staticfiles %} {% load widget_tweaks %} {% block title %}Change Password{% endblock title %} {% block content %}

<h1>Password change successful</h1>
<p>Your password was changed.</p>
<p><a href="{% url 'lenotes:index' %}">Home</a></p>

{% endblock content %}

users/templates/users/reset_password.html
{% extends "lenotes/base.html" %} {% load staticfiles %} {% load widget_tweaks %} {% block title %}Reset Password{% endblock title %} {% block stylesheet %} {% endblock stylesheet %} {% block content %}

<div class="section">
    <form class="form-users myforms" method="post" action="{% url 'users:reset_password' %}" novalidate>
        {% csrf_token %} {% include 'users/forms/reset_password.html' %}
        <center>
            <button name="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-outline-primary" href="{% url 'lenotes:index'%}">Go Back</a>
        </center>
    </form>
</div>

{% endblock content %}

users/templates/users/send_message.html
{% extends "lenotes/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Send a new message:</h2>
{% endblock header %} {% block content %}

<form action="{% url 'users:send_message' %}" method="POST" class="form">{% csrf_token %}

    <div class="form-group">
        <label for="receiver_id">Receiver ID</label>
        <input type="text" class="form-control" name="receiver_id">

        <label for="content">Content</label>
        <input type="text" class="form-control" name="content">
    </div>
    <button type="submit" class="btn btn-primary">Send</button>
</form>

{% endblock content %}

users/templates/users/settings.html
{% extends "lenotes/base.html" %} {% load widget_tweaks %} {% block title %}Settings{% endblock title %} {% block content %}
<div class="section">
    <form action="{% url 'users:settings' %}" enctype="multipart/form-data" method='post' novalidate class="myforms">
        {% csrf_token %}
        <h2>Settings</h2>
        <hr/> {% include 'users/forms/info_form.html' %}
        <div style="text-align: center">
            <button name="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-outline-primary" href="/">Go Back</a>
        </div>
    </form>
</div>
{% endblock content %}